export const PAYMENT_FETCH_REQUEST = "PAYMENT_FETCH_REQUEST";
export const PAYMENT_FETCH_SUCCESS = "PAYMENT_FETCH_SUCCESS";
export const PAYMENT_FETCH_FAIL = "PAYMENT_FETCH_FAIL";
export const PAYMENT_FETCH_RESET = "PAYMENT_FETCH_RESET";

export const PAYMENT_CREATE_REQUEST = "PAYMENT_CREATE_REQUEST";
export const PAYMENT_CREATE_SUCCESS = "PAYMENT_CREATE_SUCCESS";
export const PAYMENT_CREATE_FAIL = "PAYMENT_CREATE_FAIL";
